root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  v1.0/articles/quickstart: README.md
  v1.0/articles/rpc: deployment/rpc.md
  v1.0/articles/apache-to-minio: guides/apache-to-minio.md
