root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  v1.0/articles/quickstart: 'README.md'
  v1.0/articles/multi-process-workers: 'deployment/multi-process-workers.md'
  v1.0/articles/rpc: 'deployment/rpc.md'
  v1.0/articles/plugin-management: 'deployment/plugin-management.md'
  v1.0/articles/monitoring-rest-api: 'deployment/monitoring-rest-api.md'
  v1.0/articles/logging: 'deployment/logging.md'
  v1.0/articles/high-availability: 'deployment/high-availability.md'
  v1.0/articles/system-config: 'deployment/system-config.md'
  v1.0/articles/failure-scenarios: 'deployment/failure-scenarios.md'
  v1.0/articles/signals: 'deployment/signals.md'
  v1.0/articles/fluentd-ui: 'deployment/fluentd-ui.md'
  v1.0/articles/monitoring: 'deployment/monitoring.md'
  v1.0/articles/monitoring-prometheus: 'deployment/monitoring-prometheus.md'
  v1.0/articles/trouble-shooting: 'deployment/trouble-shooting.md'
  v1.0/articles/performance-tuning-single-process: 'deployment/performance-tuning-single-process.md'
  v1.0/articles/command-line-option: 'deployment/command-line-option.md'
  v1.0/articles/extract-section: 'configuration/extract-section.md'
  v1.0/articles/routing-examples: 'configuration/routing-examples.md'
  v1.0/articles/buffer-section: 'configuration/buffer-section.md'
  v1.0/articles/transport-section: 'configuration/transport-section.md'
  v1.0/articles/plugin-common-parameters: 'configuration/plugin-common-parameters.md'
  v1.0/articles/inject-section: 'configuration/inject-section.md'
  v1.0/articles/format-section: 'configuration/format-section.md'
  v1.0/articles/parse-section: 'configuration/parse-section.md'
  v1.0/articles/config-file: 'configuration/config-file.md'
  v1.0/articles/storage-section: 'configuration/storage-section.md'
  v1.0/articles/ruby: 'language/ruby.md'
  v1.0/articles/nodejs: 'language/nodejs.md'
  v1.0/articles/perl: 'language/perl.md'
  v1.0/articles/java: 'language/java.md'
  v1.0/articles/python: 'language/python.md'
  v1.0/articles/php: 'language/php.md'
  v1.0/articles/scala: 'language/scala.md'
