root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  v1.0/articles/quickstart: 'README.md'
  v1.0/articles/multi-process-workers: 'deployment/multi-process-workers.md'
  v1.0/articles/rpc: 'deployment/rpc.md'
  v1.0/articles/plugin-management: 'deployment/plugin-management.md'
  v1.0/articles/monitoring-rest-api: 'deployment/monitoring-rest-api.md'
  v1.0/articles/logging: 'deployment/logging.md'
  v1.0/articles/high-availability: 'deployment/high-availability.md'
  v1.0/articles/system-config: 'deployment/system-config.md'
  v1.0/articles/failure-scenarios: 'deployment/failure-scenarios.md'
  v1.0/articles/signals: 'deployment/signals.md'
  v1.0/articles/fluentd-ui: 'deployment/fluentd-ui.md'
  v1.0/articles/monitoring: 'deployment/monitoring.md'
  v1.0/articles/monitoring-prometheus: 'deployment/monitoring-prometheus.md'
  v1.0/articles/trouble-shooting: 'deployment/trouble-shooting.md'
  v1.0/articles/performance-tuning-single-process: 'deployment/performance-tuning-single-process.md'
  v1.0/articles/command-line-option: 'deployment/command-line-option.md'
  v1.0/articles/extract-section: 'configuration/extract-section.md'
  v1.0/articles/routing-examples: 'configuration/routing-examples.md'
  v1.0/articles/buffer-section: 'configuration/buffer-section.md'
  v1.0/articles/transport-section: 'configuration/transport-section.md'
  v1.0/articles/plugin-common-parameters: 'configuration/plugin-common-parameters.md'
  v1.0/articles/inject-section: 'configuration/inject-section.md'
  v1.0/articles/format-section: 'configuration/format-section.md'
  v1.0/articles/parse-section: 'configuration/parse-section.md'
  v1.0/articles/config-file: 'configuration/config-file.md'
  v1.0/articles/storage-section: 'configuration/storage-section.md'
  v1.0/articles/ruby: 'language/ruby.md'
  v1.0/articles/nodejs: 'language/nodejs.md'
  v1.0/articles/perl: 'language/perl.md'
  v1.0/articles/java: 'language/java.md'
  v1.0/articles/python: 'language/python.md'
  v1.0/articles/php: 'language/php.md'
  v1.0/articles/scala: 'language/scala.md'
  v1.0/articles/api-plugin-helper-inject: 'developer/api-plugin-helper-inject.md'
  v1.0/articles/plugin-test-code: 'developer/plugin-test-code.md'
  v1.0/articles/api-plugin-helper-thread: 'developer/api-plugin-helper-thread.md'
  v1.0/articles/api-plugin-storage: 'developer/api-plugin-storage.md'
  v1.0/articles/api-plugin-helper-compat_parameters: 'developer/api-plugin-helper-compat_parameters.md'
  v1.0/articles/api-plugin-helper-timer: 'developer/api-plugin-helper-timer.md'
  v1.0/articles/api-plugin-helper-event_loop: 'developer/api-plugin-helper-event_loop.md'
  v1.0/articles/api-plugin-base: 'developer/api-plugin-base.md'
  v1.0/articles/api-plugin-buffer: 'developer/api-plugin-buffer.md'
  v1.0/articles/api-plugin-helper-record_accessor: 'developer/api-plugin-helper-record_accessor.md'
  v1.0/articles/api-plugin-formatter: 'developer/api-plugin-formatter.md'
  v1.0/articles/api-plugin-helper-parser: 'developer/api-plugin-helper-parser.md'
  v1.0/articles/api-plugin-helper-formatter: 'developer/api-plugin-helper-formatter.md'
  v1.0/articles/api-config-types: 'developer/api-config-types.md'
  v1.0/articles/api-plugin-filter: 'developer/api-plugin-filter.md'
  v1.0/articles/api-plugin-helper-child_process: 'developer/api-plugin-helper-child_process.md'
  v1.0/articles/plugin-development: 'developer/plugin-development.md'
  v1.0/articles/api-plugin-helper-event_emitter: 'developer/api-plugin-helper-event_emitter.md'
  v1.0/articles/api-plugin-helper-server: 'developer/api-plugin-helper-server.md'
  v1.0/articles/api-plugin-helper-extract: 'developer/api-plugin-helper-extract.md'
  v1.0/articles/api-plugin-input: 'developer/api-plugin-input.md'
  v1.0/articles/api-plugin-helper-storage: 'developer/api-plugin-helper-storage.md'
  v1.0/articles/api-plugin-helper-socket: 'developer/api-plugin-helper-socket.md'
  v1.0/articles/api-plugin-output: 'developer/api-plugin-output.md'
  v1.0/articles/plugin-update-from-v0.12: 'developer/plugin-update-from-v0.12.md'
  v1.0/articles/api-plugin-parser: 'developer/api-plugin-parser.md'
  v1.0/articles/plugin-helper-overview: 'developer/plugin-helper-overview.md'
  v1.0/articles/support: 'overview/support.md'
  v1.0/articles/quickstart: 'overview/quickstart.md'
  v1.0/articles/update-from-v0.12: 'overview/update-from-v0.12.md'
  v1.0/articles/life-of-a-fluentd-event: 'overview/life-of-a-fluentd-event.md'
  v1.0/articles/logo: 'overview/logo.md'
  v1.0/articles/faq: 'overview/faq.md'
