[build]
  command = "./scripts/build.sh"
  publish = "_book"

[[redirects]]
  from = "/.gitbook/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/0.12/.gitbook/assets/*"
  to = "/0.12/assets/:splat"
  status = 200

[[redirects]]
  from = "/1.0/.gitbook/assets/*"
  to = "/1.0/assets/:splat"
  status = 200

# follow "from .gitbook/assets" rewrite rule
[[headers]]
  for = "/.gitbook/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/1.0/.gitbook/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/0.12/.gitbook/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# weekly cache (7 * 86400)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/1.0/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/0.12/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/1.0/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/0.12/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/gitbook/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/1.0/gitbook/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/0.12/gitbook/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# for custom theme
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/1.0/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/0.12/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Cache search index, it cover 1.0,0.12 too
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
